/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yingke_mediacodec_compose_AudioMixJni */

#ifndef _Included_com_yingke_mediacodec_compose_AudioMixJni
#define _Included_com_yingke_mediacodec_compose_AudioMixJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yingke_mediacodec_compose_AudioMixJni
 * Method:    audioMix
 * Signature: ([B[B[BFF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_yingke_mediacodec_compose_AudioMixJni_audioMix
  (JNIEnv *, jclass type, jbyteArray sourceA_, jbyteArray sourceB_, jbyteArray dst_, jfloat firstVol, jfloat secondVol);

#ifdef __cplusplus
}
#endif
#endif
